### ISSUE TITLE
FTBFS with GCC 5.3.1: error: 'SDL_SCANCODE_F8' undeclared

### ISSUE THREAD

**Issue by akien-mga** [sobomax/digger#1]
Hi,

I'm trying to build the master branch on Mageia 6 with GCC 5.3.1 and SDL 1.2.15, but I get this error:

```
[ 45%] Building C object CMakeFiles/digger.dir/input.c.o
In file included from /home/akien/Mageia/Checkout/digger/digger/input.c:11:0:
/home/akien/Mageia/Checkout/digger/digger/input.c: In function 'checkkeyb':
/home/akien/Mageia/Checkout/digger/digger/sdl_kbd.h:39:17: error: 'SDL_SCANCODE_F8' undeclared (first use in this function)
 #define ASCIIF8 SDL_SCANCODE_F8
                 ^
```

**Comment by sobomax** [comment]
Hmm, I cannot reproduce this with the normal make and gcc 5.3.0 in Ubuntu. Please note that cmake is not really supported or maintained, somebody contributed that file, but it's not being maintained at the moment. Also please note that libSDL-1 code has been depreciated, I am not testing with that anymore. Please use libSDL-2.0 instead. Thanks!

**Comment by akien-mga** [comment]
Yeah I guessed that something was wrong too when seeing that the CMakeLists.txt forces the usage of SDL 1.2 and does not give the possibility to select SDL2. I guess you should either drop the CMake stuff or update it, it's misleading (usually in projects where I see both a CMakeLists.txt and a good old makefile, I assume that the former is more up-to-date - though here I hadn't noticed the makefile at all).

**Comment by sobomax** [comment]
Yes, you are absolutely right. Removed, thanks!
